### ISSUE TITLE
Add Makefiles for examples?

### ISSUE THREAD

**Issue by brtchip-gdm** [BRTSG-FOSS/ft90x-sdk#22]
This might be a good idea for users who do not compile in Eclipse.

**Comment by BrtChipDatHoTan** [comment]
I will prepare one example app including the Cmake and the VSCode configured like your suggestion.

**Comment by brtchip-gdm** [comment]
Would the provision of build files for ```cmake``` would be preferable to ```make```?

**Comment by BrtChipDatHoTan** [comment]
> Would the provision of build files for `cmake` would be preferable to `make`?

Ya, we can create a Makefile. It is suitable to have. CMake is quite popular but the Makefile is suitable for the example. So I can use the Makefile first and the CMake can be an addon in the future (I still investigate the Toolchain.cmake file for the example also). We can provide multiple ways for users to build.

**Comment by brtchip-gdm** [comment]
VCCode and Eclipse project and build files can co-exist in each Examples folder.

**Comment by BrtChipDatHoTan** [comment]
So I can keep the ".vscode" folder, which contains the configuration for each example folder in VSCode.

**Comment by brtchip-gdm** [comment]
Closed with https://github.com/Bridgetek/ft9xx-sdk/pull/32 followed by https://github.com/Bridgetek/ft9xx-sdk/pull/33
