### ISSUE TITLE
Improve GPIO peripheral mapping

### ISSUE THREAD

**Issue by brtchip-gdm** [BRTSG-FOSS/ft90x-sdk#37]
Match GPIO numbers and pad numbers for ```gpio_function()``` calls. There is only one GPIO (i.e. external pin) available for each peripheral function. Therefore the 2 parameters for gpio_function are intrinsically related. Definitions will be made in ```ft900_gpio.h```.

**Comment by brtchip-gdm** [comment]
@BrtChipDatHoTan please check the branch for this work and close.

**Comment by BrtChipDatHoTan** [comment]
It looks good to me thank you.
