### ISSUE TITLE
Incorrect prototypes added for compiler warnings.

### ISSUE THREAD

**Issue by brtchip-gdm** [BRTSG-FOSS/ft90x-sdk#41]
https://github.com/Bridgetek/ft9xx-sdk/blame/1b998d5fe6c2e2fa7077a67e81af339220fa6c79/Source/src/usbd.c#L381
The weak functions are called USBDX_pipe_isr, USBDX_pipe_isr_start and USBDX_pipe_isr_end.

**Comment by brtchip-gdm** [comment]
@BrtChipDatHoTan I've removed the forward declarations. Does not affect compilation.

**Comment by BrtChipDatHoTan** [comment]
Ya, it looks good to me. Thank you for finding this one.
