### ISSUE TITLE
USB Finalise

### ISSUE THREAD

**Issue by BRTCHIP-GB** [BRTSG-FOSS/ft90x-sdk#52]
USB Finalise does not turn off the power to the USB host port on the MM900EV1B

**Comment by brtchip-gdm** [comment]
There is a fix for this in the branch for #47 (the issues are related).
The GPIO2 pin is used by the `usbh.c` code to enable power to the downstream device during the `USBH_initialise` call (`usbh_hw_pad_setup`). A suitable call to reverse this is performed within `USBH_finalise`.
I am investigating whether this action should be performed with a SET/CLEAR_FEATURE(PORT_POWER) for the root hub.

**Comment by brtchip-gdm** [comment]
The `usbh.c` driver does not ever turn the root hub power off. It is turned on during `USBH_initialise` and left on. This change should be OK but testing will continue as part of #51

**Comment by BRTCHIP-GB** [comment]
Thanks, that fix works well
